image: hugomods/hugo

before_script:
  - apk add imagemagick libwebp libjpeg bash git
  - git submodule update --init --remote --recursive themes/mainroad
  - ./process_images.sh

build:
  script:
    - hugo --cleanDestinationDir --gc --ignoreCache --minify
  artifacts:
    paths:
      - public/

pages:
  script:
    - hugo --baseURL "https://mtimm_01.zivgitlabpages.uni-muenster.de/blog/" --cleanDestinationDir --gc --ignoreCache --minify
  artifacts:
    paths:
      - public/