stages:
  - build

build-site:
  - image: jguyomard/hugo-builder
  - stage: build
    before_script:
    - apk --update add minify imagemagick
    script:
    - hugo
    - ./minify.sh
    - ./process_images.sh
