image: jguyomard/hugo-builder

before_script:
- apk --update add imagemagick

build:site:
  script:
  - hugo
  - echo $HOME
  - /bin/sh /builds/mtimm_01/blog/process_images.sh
  artifacts:
    paths:
    - public/
