image: node:latest

before_script:
  - ./updatePostList.sh > ./postdata.json
  - ./process_images.sh
  - patch -p0 ./docs/.vitepress/config.ts < ./docs/.vitepress/config_ci_pages.patch
  - find ./docs/public/img -type f -name '*.jpg' -exec rm {} \;
  - npm install

pages:
  script:
  - npm run docs:build
  - mv docs/.vitepress/dist public
  artifacts:
    paths:
    - public
