image: jguyomard/hugo-builder

before_script:
- apk --update add imagemagick

pages:
  script:
  - hugo --baseURL https://mtimm_01.zivgitlabpages.uni-muenster.de/blog/
  - echo $HOME
  - /bin/sh /builds/mtimm_01/blog/process_images.sh
  artifacts:
    paths:
    - public/
