baseURL = "https://mariustimmer.de/"
languageCode = "de"
theme = "binario"
DefaultContentLanguage = "de"
rssLimit = 10
enableRobotsTXT = false

[taxonomies]
    tag = "tags"
    category = "categories"

[sitemap]
    changefreq = "daily"

[languages]
    [languages.en]
        title = "Timmers blog"
        languageName = "English"
        description = "Personal blog of Marius Timmer"
        weight = 1
        [[languages.en.menu.main]]
            url    = "/en/"
            name   = "Home"
            weight = 1

        [[languages.en.menu.main]]
            url    = "/en/post/"
            name   = "All posts"
            weight = 2

        [[languages.en.menu.main]]
            url    = "/en/photos/"
            name   = "Photography"
            weight = 3

        [[languages.en.menu.main]]
            url    = "/en/references/"
            name   = "References"
            weight = 4

        [[languages.en.menu.main]]
            url    = "/en/aboutme/"
            name   = "About Me"
            weight = 5

        [[languages.en.menu.icon]]
            url    = "mailto:admin@mariustimmer.de"
            name   = "envelope-o"
            weight = 1

        [[languages.en.menu.icon]]
            url    = "https://twitter.com/marius_timmer?lang=en"
            name   = "twitter"
            weight = 2

        [[languages.en.menu.icon]]
            url    = "https://github.com/mariustimmer/"
            name   = "github"
            weight = 3

        [[languages.en.menu.icon]]
            url    = "https://twitch.tv/topster"
            name   = "twitch"
            weight = 4

        [[languages.en.menu.icon]]
            url    = "https://www.youtube.com/channel/UCKllWK67NhLhk6QAwLelVyA"
            name   = "youtube"
            weight = 5

    [languages.de]
        title = "Timmers Blog"
        languageName = "Deutsch"
        description = "Persönlicher Blog von Marius Timmer"
        weight = 2
        [[languages.de.menu.main]]
            url    = "/"
            name   = "Start"
            weight = 1

        [[languages.de.menu.main]]
            url    = "/post/"
            name   = "Alle Beiträge"
            weight = 2

        [[languages.de.menu.main]]
            url    = "/photos/"
            name   = "Fotografie"
            weight = 3

        [[languages.de.menu.main]]
            url    = "/references/"
            name   = "Referenzen"
            weight = 4

        [[languages.de.menu.main]]
            url    = "/aboutme/"
            name   = "Über Mich"
            weight = 5

        [[languages.de.menu.icon]]
            url    = "mailto:admin@mariustimmer.de"
            name   = "envelope-o"
            weight = 1

        [[languages.de.menu.icon]]
            url    = "https://twitter.com/marius_timmer?lang=de"
            name   = "twitter"
            weight = 2

        [[languages.de.menu.icon]]
            url    = "https://github.com/mariustimmer/"
            name   = "github"
            weight = 3

        [[languages.de.menu.icon]]
            url    = "https://twitch.tv/topster"
            name   = "twitch"
            weight = 4

        [[languages.de.menu.icon]]
            url    = "https://www.youtube.com/channel/UCKllWK67NhLhk6QAwLelVyA"
            name   = "youtube"
            weight = 5

[params]
    author = "Marius Timmer"
    twitter_username = "@marius_timmer"
    copyright = "Marius Timmer"
    githubUsername = "#mariustimmer"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["php", "bash"]
    related = true
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
