baseURL = "https://mariustimmer.de/"
languageCode = "de"
theme = "minimal"
DefaultContentLanguage = "de"
rssLimit = 10
enableRobotsTXT = true

[taxonomies]
    tag = "tags"
    category = "categories"

[sitemap]
    changefreq = "daily"

[languages]
    [languages.en]
        title = "Timmers blog"
        languageName = "English"
        description = "Personal blog of Marius Timmer"
        copyright = "&copy; 2019 by Marius Timmer"
        weight = 1
        [[languages.en.menu.main]]
            url = "/en/"
            name = "Home"
            weight = 1

        [[languages.en.menu.main]]
            url = "/en/post/"
            name = "Posts"
            weight = 2

        [[languages.en.menu.main]]
            url = "/polen_2018/"
            name = "Poland"
            weight = 3

        [[languages.en.menu.main]]
            url = "/en/references/"
            name = "References"
            weight = 4

        [[languages.en.menu.main]]
            url = "/en/aboutme/"
            name = "About Me"
            weight = 5

        [[languages.en.menu.icon]]
            url = "mailto:admin@mariustimmer.de"
            name = "envelope-o"
            weight = 1

        [[languages.en.menu.icon]]
            url = "https://github.com/mariustimmer/"
            name = "github"
            weight = 2

        [[languages.en.menu.icon]]
            url = "https://twitch.tv/topster"
            name = "twitch"
            weight = 3

        [[languages.en.menu.icon]]
            url = "https://www.youtube.com/channel/UCKllWK67NhLhk6QAwLelVyA"
            name = "youtube"
            weight = 4

    [languages.de]
        title = "Timmers Blog"
        languageName = "Deutsch"
        description = "Persönlicher Blog von Marius Timmer"
        copyright = "&copy; 2019 durch Marius Timmer"
        weight = 2
        [[languages.de.menu.main]]
            url = "/"
            name = "Start"
            weight = 1

        [[languages.de.menu.main]]
            url = "/post/"
            name = "Beiträge"
            weight = 2

        [[languages.de.menu.main]]
            url = "/polen_2018/"
            name = "Polen"
            weight = 3

        [[languages.de.menu.main]]
            url = "/references/"
            name = "Referenzen"
            weight = 4

        [[languages.de.menu.main]]
            url = "/aboutme/"
            name = "Über Mich"
            weight = 5

        [[languages.de.menu.icon]]
            url = "mailto:admin@mariustimmer.de"
            name = "envelope-o"
            weight = 1

        [[languages.de.menu.icon]]
            url = "https://github.com/mariustimmer/"
            name = "github"
            weight = 2

        [[languages.de.menu.icon]]
            url = "https://twitch.tv/topster"
            name = "twitch"
            weight = 3

        [[languages.de.menu.icon]]
            url = "https://www.youtube.com/channel/UCKllWK67NhLhk6QAwLelVyA"
            name = "youtube"
            weight = 4

[params]
    author = "Marius Timmer"
    githubUsername = "#mariustimmer"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["php", "bash"]
